namespace ExterView.Api.Services;

public interface IMockGraphService
{
    Task<string> GetTranscriptAsync(string meetingId);
}

public class MockGraphService : IMockGraphService
{
    private readonly ILogger<MockGraphService> _logger;
    private readonly IConfiguration _configuration;
    private readonly Random _random = new();

    public MockGraphService(ILogger<MockGraphService> logger, IConfiguration configuration)
    {
        _logger = logger;
        _configuration = configuration;
    }

    public async Task<string> GetTranscriptAsync(string meetingId)
    {
        // Simulate delay (transcript not immediately available after meeting ends)
        var simulateDelay = _configuration.GetValue<bool>("MockGraphService:SimulateDelay", true);
        if (simulateDelay)
        {
            var minDelay = _configuration.GetValue<int>("MockGraphService:MinDelayMs", 500);
            var maxDelay = _configuration.GetValue<int>("MockGraphService:MaxDelayMs", 2000);
            var delay = _random.Next(minDelay, maxDelay);
            await Task.Delay(delay);
        }

        _logger.LogInformation("Mock Graph API: Fetched transcript for meeting {MeetingId}", meetingId);

        // Return mock transcript content
        return $@"Microsoft Teams Meeting Transcript
Meeting ID: {meetingId}
Date: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss UTC}

[00:00:05] Speaker 1: Welcome to the interview. Thank you for joining us today.
[00:00:15] Speaker 2: Thank you for having me. I'm excited to be here.
[00:00:30] Speaker 1: Let's start with a quick introduction. Can you tell me about your experience with C# and .NET?
[00:01:00] Speaker 2: Sure! I have 5 years of experience building enterprise applications using C# and .NET.
[00:01:20] Speaker 2: I've worked extensively with ASP.NET Core, Entity Framework, and Azure services.
[00:01:45] Speaker 1: That's great. Have you worked with Microsoft Teams integrations before?
[00:02:00] Speaker 2: Yes, I've built several Teams bots using the Bot Framework SDK.
[00:02:15] Speaker 2: I've also integrated with Microsoft Graph API for calendar and user management.
[00:02:45] Speaker 1: Excellent. Can you describe a challenging problem you've solved recently?
[00:03:00] Speaker 2: Recently, I implemented a distributed transaction processing system with idempotency guarantees.
[00:03:20] Speaker 2: The challenge was ensuring no duplicate operations while handling high throughput.
[00:03:40] Speaker 2: I used a combination of PostgreSQL unique constraints and distributed locks.
[00:04:00] Speaker 1: Impressive. Do you have any questions for us?
[00:04:15] Speaker 2: Yes, what are the main technical challenges your team is currently facing?
[00:04:30] Speaker 1: We're scaling our platform to handle 10,000 meetings per day.
[00:04:45] Speaker 1: We need expertise in async processing, retry logic, and cloud architecture.
[00:05:00] Speaker 2: That sounds like a great challenge. I'd love to contribute.
[00:05:15] Speaker 1: Thank you for your time today. We'll be in touch soon.
[00:05:25] Speaker 2: Thank you! Looking forward to hearing from you.

[End of Transcript]
Generated by: ExterView Assessment Bot
";
    }
}
